server.port=1972
api.base.path=/c2/lc/ms
fetch.max.size.limit=500
eventhub.name=dev-notification
eventhub.connection.string=Endpoint=sb://ms-notification.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=eUARr/UWu1AXXtl420Rprf6GrZnRgyTFF0cvGk0KiZA=