server.port=1974
api.base.path=/c2/lc/ms
fetch.max.size.limit=500

eventhub.name=dev-notification
eventhub.connection.string=Endpoint=sb://ms-notification.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=eUARr/UWu1AXXtl420Rprf6GrZnRgyTFF0cvGk0KiZA=

# Email credentials for Gmail account
gmail.smtp.user=noreply.microservices@c2info.com
gmail.smtp.userName=noreply.microservices@c2info.com
gmail.smtp.password=M!cr0#158

#Telegram bot
telegram.chat.id=-631957479
telegram.url.sendMessage=https://api.telegram.org/bot5504325370:AAFebig5S22g6vfzuq9QpqS3VDQ__RBfTsM/sendMessage